Added Unit tests
ggupta9777/simple_line_follower pull request #1
Opened 2023-11-21 08:56 UTC by topguns837

- [x] Made the line_follower and naive_line_follower compile
- [x] Added basic unit tests for both line_follower and naive_line_follower
- [x]  Added good unit tests for line_follower

2023-11-21 13:19 UTC, ggupta9777 requested changes

2023-11-21 13:19 UTC, ggupta9777 commented on src/naive_line_follower.cpp
> -    geometry_msgs::msg::TransformStamped transformStamped;
Use underscores for variable names all the way through

2023-11-21 13:19 UTC, ggupta9777 commented on src/naive_line_follower.cpp
> +      if (bot_yaw<=0){
Should be <, not <=

2023-11-21 13:19 UTC, ggupta9777 commented on src/naive_line_follower.cpp
> +
We don't need the initial alignment, we make the assumption that robot is sufficiently well aligned to begin with.

2023-11-21 13:19 UTC, ggupta9777 commented on src/naive_line_follower.cpp
> +      double k_p = 0.1;
Initialize in constructor. Make a function called setControlGain to change this if needed.

2023-11-21 13:19 UTC, ggupta9777 commented on src/naive_line_follower.cpp
> +      cmd_vel_.linear.x = 1.0; // constant forward velocity
Move this to the constructor

2023-11-21 13:19 UTC, ggupta9777 commented on src/naive_line_follower.cpp
> +    std::chrono::milliseconds(100),
Control loop should faster, say at least 20 Hz

2023-11-21 13:19 UTC, ggupta9777 commented on src/line_follower.cpp
> +  double k_p = 0.1; // Proportional gain
Similar to naive implementation, this should be set from a function overriding the default value from constructor

2023-11-21 13:19 UTC, ggupta9777 commented on test/test_line_follower_poor.cpp
> +  auto publisher_ = test_got_to_goal_node->create_publisher<tf2_msgs::msg::TFMessage>("tf", 10);
This isn't a class member, so no underscore is needed as a suffix

2023-11-21 13:19 UTC, ggupta9777 commented on test/test_line_follower_poor.cpp
> +  bool received_twist=false;
You can add a space on either side. Refer to cpp lint for the code in general

2023-11-21 13:19 UTC, ggupta9777 commented on test/test_line_follower.cpp
> +TEST_F(TestLineFollower, TestIdenticalWaypoints)
This test doesn't contribute meaningfully to the code so we should remove it

2023-11-27 09:48 UTC, ggupta9777 commented
![Screenshot from 2023-11-27 15-16-34](https://github.com/ggupta9777/simple_line_follower/assets/13151010/d9e57850-84bf-450b-9a47-691c54158380)

@topguns837 - can we remove these compile warnings?

2023-11-27 20:06 UTC, topguns837 commented
> ![Screenshot from 2023-11-27 15-16-34](https://private-user-images.githubusercontent.com/13151010/285810029-d9e57850-84bf-450b-9a47-691c54158380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTU4NjUsIm5iZiI6MTcwMTExNTU2NSwicGF0aCI6Ii8xMzE1MTAxMC8yODU4MTAwMjktZDllNTc4NTAtODRiZi00NTBiLTlhNDctNjkxYzU0MTU4MzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDIwMDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmY2QyZjE0NWU0OGMxMjllMmQ0ZDQ1MWEzMTMwNTIzNGUyZTA5ODEwOWFiMDIwODA4NTRmZDhlNWM0MDg1MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCsx4nyb78qiJ512ca4_FnTw2aBDu3VmW4DOkkyR5PE)
> 
> @topguns837 - can we remove these compile warnings?

done

2023-11-30 18:22 UTC, merged